table 'Gold dim_customers'
	lineageTag: 7a953885-95d7-4b52-82cf-77835a8146e0

	column customer_key
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 2a4b0e1b-705a-4a17-ac59-de2c2c2f6f49
		summarizeBy: none
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	column customer_number
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2940bc55-346e-498f-be2b-3acc73a7bdcb
		summarizeBy: sum
		sourceColumn: customer_number

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: f509aca1-419d-43ec-8a06-8ff1df26bf64
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 039382d4-cf7a-4a3c-9ead-20fc33fd0cda
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 8979489a-5da6-47a2-a740-ff7486961b15
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column marital_status
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: fb1d6093-d880-4de2-b377-f0335b768483
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

	column birth_date
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 9b25ddc3-a065-4a5d-9ad7-3203bca8ba61
		summarizeBy: none
		sourceColumn: birth_date

		variation Variation
			isDefault
			relationship: 713146fb-f68f-4830-824a-3b884cc47c5c
			defaultHierarchy: LocalDateTable_61c80ffe-7fec-415b-902a-db29f13fe562.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column create_date
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 102ea13a-3e62-456c-a76d-c42e79405821
		summarizeBy: none
		sourceColumn: create_date

		variation Variation
			isDefault
			relationship: 5a8cb472-ae24-4065-a1dd-4f01b9e48689
			defaultHierarchy: LocalDateTable_54f814cd-e459-4b4d-9c29-d31b4c4ce531.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Customer Age' = DATEDIFF('Gold dim_customers'[birth_date], TODAY(), YEAR)
		formatString: 0
		lineageTag: 73ec459b-384b-410d-95cf-ba73aca6b7fc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Age Category' = ```
			
			    SWITCH(TRUE(),
			            AND([Customer Age]>= 0,[Customer Age]<=10), "0 - 10", 
			            AND([Customer Age]>= 11,[Customer Age]<=20), "11 - 20",
			            AND([Customer Age]>= 21,[Customer Age]<=30), "21 - 30",
			            AND([Customer Age]>= 31,[Customer Age]<=40), "31 - 40",
			            AND([Customer Age]>= 41,[Customer Age]<=50), "41 - 50",
			            AND([Customer Age]>= 51,[Customer Age]<=60), "51 - 60",
			            AND([Customer Age]>= 61,[Customer Age]<=70), "61 - 70",
			            "70 +"
			    )
			```
		lineageTag: fdf9a6e8-4ff5-453d-93d7-8c554a3296a9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		sourceProviderType: nvarchar(101)
		lineageTag: 415be6f6-22ce-4d98-9728-a02c2e51e3f5
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'customer type' = ```
			
			    VAR _TotalOrders = [Number of Transcactions]
			    VAR _TotalQuantity = [Quantity]
			    
			
			RETURN
			        IF(
			            AND(_TotalOrders>=2,_TotalQuantity>10),
			            "VIP",
			                IF(_TotalOrders>=2,
			                    "Loyal",
			                    "Periodic"
			                )
			        )
			```
		lineageTag: 6f3abb0c-5b0b-438e-9ba2-ff2a82213229
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Gold dim_customers' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("DESKTOP-SG4BLSV\SQLEXPRESS"),
				    Datawarehouse = Source{[Name="Datawarehouse"]}[Data],
				    Gold_dim_customers = Datawarehouse{[Schema="Gold",Item="dim_customers"]}[Data],
				    #"Merged Columns" = Table.CombineColumns(Gold_dim_customers,{"first_name", "last_name"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Name")
				in
				    #"Merged Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

